name: Rust

on: workflow_dispatch


env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:

    runs-on: self-hosted-manjaro

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      continue-on-error: true
      run: cargo clippy
    - name: Tests
      run: cargo test --verbose